src/main/java/com/grepp/diary/App.java, src/main/java/com/grepp/diary/app/model/test3.java
- 개발을 위해 일시적으로 Spring Security 를 비활성화 했습니다.
=> :construction: Disable Spring Security

src/main/java/com/grepp/diary/app/controller/web/admin/AdminController.java, src/main/resources/templates/admin/admin-main.html, src/main/resources/templates/fragments.html
admin 메인 페이지 불러오고, 사이드 바를 fragments.html 파일에 따로 분리해두었습니다.
공통으로 필요한 컴포넌트의 경우 fragments.html 파일에 적어두시고 활용하는 방법도 좋을 것 같습니다!
=> ✨create admin main page & separate side-bar at fragements.html

src/main/resources/static/css/main.css, src/main/resources/static/css/sidebar.css, src/main/resources/templates/app/index.html, src/main/resources/templates/fragments/member-sidebar.html
:lipstick: Separate sidebar html/css
- 사이드메뉴와 관련된 Html코드와 Css를 분리하였습니다.
=> :lipstick: Separate sidebar html/css

src/main/resources/data.sql, src/main/resources/static/css/calendar.css, src/main/resources/static/css/sidebar.css, src/main/resources/static/js/calendar.js, src/main/resources/templates/app/index.html, src/main/resources/templates/fragments/member-sidebar.html
- 마우스 hover 이벤트를 감지하여, 마우스가 사이드메뉴에 올라왔을때 확장되도록 하였습니다.
- 사이드 메뉴 하단에 로그아웃 버튼을 추가하였습니다.
- 사이드 메뉴의 각 버튼에 아이콘을 추가하였습니다. (Font awesome)
- 메인 페이지에 캘린더 UI를 구현하였습니다.
- 이전달로 이동, 다음달로 이동 버튼이 구현되었습니다.
- 오늘로 이동 버튼이 구형되었습니다.
- 기존의 Data.sql에서 member테이블의 데이터 중 admin과 관련된 데이터를 수정하였습니다.
- AI 테이블과 CUSTOM 테이블에 관련된 데이터를 추가하였습니다.
- IMAGE 테이블에 대한 데이터는 이미지 삽입 구현후 직접 테스트 해보는게 나을 것 같아 추가하지 않았습니다.
- REPLY 테이블에 대한 데이터는 미리 추가해두는게 좋을지 판단이 서지 않아 의논후 결정하는것이 좋을 것 같습니다.
=> New & Changes on MainPage UI / Add data for tests

src/main/java/com/grepp/diary/app/model/common/entity/BaseEntity.java
- BaseEntity에 getter가 없어 시간정보를 가져올 수 없던 문제가 발생하여 관련된 어노테이션들을 추가했습니다.
=> :sparkles: Add getter, setter, toString annotations in BaseEntity.java

src/main/java/com/grepp/diary/app/controller/web/app/AppController.java, src/main/resources/static/css/calendar.css, src/main/resources/static/css/error/error.css, src/main/resources/static/css/index.css, src/main/resources/static/css/login.css, src/main/resources/static/css/main.css, src/main/resources/static/css/sidebar.css, src/main/resources/static/js/sidebar.js, src/main/resources/templates/app/home.html, src/main/resources/templates/error/404.html, src/main/resources/templates/index.html
- 기존의 홈화면 및 사이드 메뉴의 색을 변경했습니다.
- 기존의 로그인 화면 ui를 변경했습니다.
- 404에러 발생시 나타날 화면을 추가했습니다.
=> UI Changes

src/main/java/com/grepp/diary/app/controller/web/IndexController.java, src/main/java/com/grepp/diary/app/controller/web/auth/AuthController.java, src/main/java/com/grepp/diary/app/controller/web/auth/form/SignupForm.java, src/main/java/com/grepp/diary/app/model/auth/AuthService.java, src/main/java/com/grepp/diary/app/model/member/MemberService.java, src/main/java/com/grepp/diary/infra/config/SecurityConfig.java, src/main/resources/static/css/index.css, src/main/resources/templates/index.html, src/main/resources/templates/member/regist.html
로그인, 회원가입 기능 구현
로그인 기능 구현 , 회원가입 페이지 + 기능 구현
- SecurityConfig 추가 = 지금은 개발초기라 permitall로 로그인안해도 다 뚫리게 해놨습니다.
- 비밀번호 암호화, 복호화해놓아서 기존 더미데이터들로는 로그인 불가능하고 새로 회원가입해야 로그인 가능합니다.
- 이메일 인증기능은 미구현입니다.
- controller 위주로 봐주시면 될 것 같습니다.
=> ✨ implement login & registration page(without email verification)

pom.xml
=> :heavy_minus_sign: Remove duplicated dependency

.gitignore, src/main/java/com/grepp/diary/infra/config/PropertyConfig.java, src/main/resources/application.properties, src/main/resources/static/css/sidebar.css, src/main/resources/templates/fragments/member-sidebar.html
- properties에 작성되어있던 이메일을 제거했습니다.
##🙈 Update gitignore
- env파일 사용을 위해 gitignore 수정
- 타임라인 메뉴가 추가되었습니다.
- 메뉴클릭이 아이콘과 텍스트에만 적용되는 문제를 해결했습니다. 이제 해당 메뉴가 있는 구역이면 전부 클릭됩니다.
=> Improve Sidebar UI & Update properties

src/main/java/com/grepp/diary/app/controller/api/auth/AuthApiController.java, src/main/java/com/grepp/diary/app/controller/api/auth/payload/OnboardingRequest.java, src/main/java/com/grepp/diary/app/controller/web/app/AppController.java, src/main/java/com/grepp/diary/app/controller/web/auth/AuthController.java, src/main/java/com/grepp/diary/app/model/ai/AiRepository.java, src/main/java/com/grepp/diary/app/model/custom/CustomService.java, src/main/java/com/grepp/diary/app/model/custom/repository/CustomRepository.java, src/main/java/com/grepp/diary/infra/config/SecurityConfig.java, src/main/resources/static/css/onboarding-qna.css, src/main/resources/static/css/onboarding-result.css, src/main/resources/static/css/onboarding.css, src/main/resources/static/js/onboarding-qna.js, src/main/resources/templates/onboarding/onboarding-qna.html, src/main/resources/templates/onboarding/onboarding-result.html, src/main/resources/templates/onboarding/onboarding.html
ai- 초기질문 구현
- ai 초기질문 4가지 qna 프론트 & 백 구현 
- spring security csrf ingored 처리
- 이제 모든 요청 permitall로 안함. 따라서 새로 회원가입 후 로그인해야 다른 페이지로 접속가능함
=> ai 초기질문 & 시큐리티 url 제한두고 csrf 제한둠

src/main/java/com/grepp/diary/app/controller/web/auth/AuthController.java, src/main/java/com/grepp/diary/app/model/ai/AiRepository.java, src/main/resources/static/css/ai-management.css
=> 🐛fix ai repository path

src/main/java/com/grepp/diary/app/controller/web/auth/AuthController.java, src/main/resources/static/js/sidebar.js, src/main/resources/templates/app/member-dashboard.html, src/main/resources/templates/app/settings/settings-ai.html, src/main/resources/templates/app/settings/settings-email.html, src/main/resources/templates/app/settings/settings-password.html, src/main/resources/templates/app/settings/settings.html
- 홈, 타임라인 페이지를 제외한 모든 페이지에서 로그아웃이 되지 않는 현상을 해결하였습니다.
- 설정 페이지의 세부 페이지에 들어갔을때, 사이드바의 메뉴색상이 유지되지 않는 현상을 해결하였습니다.
- 
- csrf태그가 없어 로그아웃되지 않는 문제를 해결하였습니다.
- 설정페이지에서 이메일 변경, 비밀번호변경, AI 캐릭터 변경 페이지에 들어갔을때, 설정 메뉴가 선택되어있지 않은 것 처럼 보이는 문제를 해결하였습니다.
- 더이상 사용하지 않는 디버그 로그 코드를 제거하였습니다.
- 단순한 UI 및  코드삭제 변경점입니다.
=> Fix Logout Issue & Sidebar Issue

src/main/java/com/grepp/diary/app/controller/api/admin/AdminApiController.java, src/main/java/com/grepp/diary/app/controller/api/admin/payload/AdminAiResponse.java, src/main/java/com/grepp/diary/app/controller/api/admin/payload/AdminAiWriteRequest.java, src/main/java/com/grepp/diary/app/controller/web/admin/AdminController.java, src/main/java/com/grepp/diary/app/model/ai/AiService.java, src/main/java/com/grepp/diary/app/model/ai/dto/AiDto.java, src/main/java/com/grepp/diary/app/model/ai/dto/AiImgDto.java, src/main/java/com/grepp/diary/app/model/ai/dto/AiWithCountDto.java, src/main/java/com/grepp/diary/app/model/ai/entity/Ai.java, src/main/java/com/grepp/diary/app/model/ai/entity/AiImg.java, src/main/java/com/grepp/diary/app/model/ai/repository/AiImgRepository.java, src/main/java/com/grepp/diary/app/model/ai/repository/AiImgRepositoryCustom.java, src/main/java/com/grepp/diary/app/model/ai/repository/AiImgRepositoryImpl.java, src/main/java/com/grepp/diary/app/model/common/code/ImgType.java, src/main/java/com/grepp/diary/app/model/custom/CustomService.java, src/main/java/com/grepp/diary/app/model/diary/DiaryService.java, src/main/java/com/grepp/diary/app/model/diary/code/DiaryImgType.java, src/main/java/com/grepp/diary/app/model/diary/entity/DiaryImg.java, src/main/java/com/grepp/diary/infra/util/file/FileUtil.java, src/main/resources/static/js/admin-ai-write.js
AI 관리에 파일 업로드 기능을 붙였습니다.
https://github.com/user-attachments/assets/70467e3f-a4dc-431a-9bb5-6cca0b5ffccb
=> AI 관리에 파일 업로드 기능을 붙였습니다.

src/main/resources/static/css/diary.css, src/main/resources/templates/diary/write-diary.html
=> :lipstick: Improve diary write page

src/main/java/com/grepp/diary/app/controller/web/auth/AuthController.java, src/main/java/com/grepp/diary/app/controller/web/member/MemberController.java, src/main/java/com/grepp/diary/app/model/auth/AuthService.java, src/main/java/com/grepp/diary/app/model/member/MemberService.java, src/main/java/com/grepp/diary/infra/config/SecurityConfig.java
리팩토링 하면서 잘못 수정된 에러 수정하였습니다.
- 아이디 찾기
- 비번 찾기
- 메일 인증 
리멤버미 기능을 수동 구현으로 바꾸었습니다.
=> 리멤버미 로직 변경 & 로그인 에러 수정 

src/main/resources/static/css/index.css, src/main/resources/templates/member/regist.html
=> 회원가입 AI 이미지 불러오기

src/main/java/com/grepp/diary/app/controller/web/app/AppController.java
🚑 이전 PR 때 AppController 에서 model.addAttribute 를 삭제했던 것을 원복
- model 로 userId 를 전달하는 코드를 원복
- model 로 List<AiDto> 를 전달하는 코드를 원복
=> 🚑️ Undo removing 2line from AppController

src/main/java/com/grepp/diary/app/controller/web/member/MemberController.java, src/main/java/com/grepp/diary/app/model/member/MemberService.java, src/main/java/com/grepp/diary/app/model/member/repository/MemberRepository.java, src/main/resources/static/css/settings.css, src/main/resources/templates/app/settings/settings-email.html
- 이메일 변경시 기존에 사용하던 이메일인경우 이메일을 변경하지 않도록 했습니다.
- 에러 발생시 사용할 배너를 이메일 변경 페이지에 추가하였습니다.
- 이메읿 변경시 기존에 사용중이던 이메일과 동일한 이메일인지 검사하는 로직을 추가하였습니다
=> Add validation to prevent changing to the current email

src/main/java/com/grepp/diary/infra/config/SecurityConfig.java, src/main/resources/static/js/admin-ai-write.js, src/main/resources/static/js/admin-ai.js, src/main/resources/static/js/admin-keyword-modal.js, src/main/resources/static/js/admin-keyword.js, src/main/resources/static/js/leave.js, src/main/resources/static/js/onboarding-qna.js, src/main/resources/templates/admin/admin-ai-write.html, src/main/resources/templates/admin/admin-ai.html, src/main/resources/templates/admin/admin-index.html, src/main/resources/templates/admin/admin-keyword.html, src/main/resources/templates/app/home.html, src/main/resources/templates/app/member-dashboard.html, src/main/resources/templates/app/settings/settings-ai.html, src/main/resources/templates/app/settings/settings-email.html, src/main/resources/templates/app/settings/settings-password.html, src/main/resources/templates/app/settings/settings.html, src/main/resources/templates/app/timeline.html, src/main/resources/templates/diary/edit.html, src/main/resources/templates/fragments/csrf-meta.html, src/main/resources/templates/member/leave.html, src/main/resources/templates/onboarding/onboarding-qna.html
관리자 페이지
회원 설정 페이지
회원 대시보드 페이지
회원 타임라인 페이지
로그아웃(관리자, 회원 설정, 회원 대시보드, 회원 타임라인)
=> csrf 토큰 권한 추가

src/main/resources/static/js/logout.js, src/main/resources/static/js/onboarding-result.js, src/main/resources/templates/diary/edit.html, src/main/resources/templates/diary/record.html, src/main/resources/templates/diary/write-diary.html, src/main/resources/templates/member/reset-password.html, src/main/resources/templates/onboarding/onboarding-result.html
1. csrf 토큰 추가
2. 회원가입- 비밀번호 복붙 막기
3. 온보딩 "다른 AI도 확인해보시겠어요?" 404오류해결
=> csrf토큰추가하고 온보딩 오류 해

src/main/resources/templates/index.html
=> 🛂 add csrf token

src/main/resources/static/js/card-list.js, src/main/resources/templates/diary/record.html
- 버그 수정
- 홈화면과 타임라인 페이지에서 일기의 날짜가 잘못 표시되는 문제 해결
- 일기 조회시 COMMON에 해당하는 이미지가 보이지 않는 문제 해결
=> Fix: Few Issues

src/main/resources/static/js/member-dashboard.js
=> :bug: Fix mood distribution chart COMMON not display
